# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  push:
    paths-ignore: "extern/**"
  pull_request:
    paths-ignore: "extern/**"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: check libc and libm
        run: |
          ldd --version
          ls /lib/x86_64-linux-gnu/libm.so.6

      - name: download ROOT
        env:
          ROOT_URL: https://root.cern/download/root_v6.22.08.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        run: |
          apt update
          apt install snap
          sudo snap install root-framework 
          snap install cmake --classic

      - name: Configure
        run: |
          root -n -b --version
          cmake --version
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: DingXuefeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks:
          ignore: build
          database: build
          extensions: cc,cu
          version: 12
          files-changed-only: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
