# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  push:
    paths-ignore: "extern/**"
  pull_request:
    paths-ignore: "extern/**"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: check libc and libm
        run: |
          ldd --version
          ls /lib/x86_64-linux-gnu/libm.so.6

      - name: download ROOT
        env:
          ROOT_URL: https://root.cern/download/root_v6.22.08.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python libssl-dev
          sudo apt-get install -y cmake wget ninja-build
          pushd ../
          mkdir root
          wget --no-check-certificate --quiet -O - "${ROOT_URL}" | tar --strip-components=1 -xz -C root
          popd

      - name: Configure
        run: |
          source ../root/bin/thisroot.sh
          cmake --version
          rm -rf build
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=g++

      - uses: DingXuefeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks:
          ignore: build
          database: build
          extensions: cc,cu
          files-changed-only: false

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
